services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env.prod
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env.prod
