# Base image
FROM node:18-alpine

# Set environment variables for pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Enable Corepack and prepare pnpm
RUN corepack enable && corepack prepare pnpm@10.11.0 --activate

# Set working directory
WORKDIR /usr/backend/dev

# Copy dependency files
COPY package.json pnpm-lock.yaml ./

# Install dependencies with caching
RUN --mount=type=cache,target=/root/.pnpm-store \
  pnpm install

# Copy application source code
COPY . .

RUN apk add --no-cache curl

# Copy entrypoint script
COPY entrypoint.sh /usr/backend/dev/entrypoint.sh
RUN chmod +x /usr/backend/dev/entrypoint.sh

# Expose application port
EXPOSE 3000

# Start the development server
CMD ["./entrypoint.sh"]
